ci: Build also Landing and UI. Include git tag to container tags

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,6 +46,7 @@ jobs:
       - name: Checkout code (with submodules)
         uses: actions/checkout@v4
         with:
+          fetch-depth: '0'
           submodules: recursive
 
       - name: Download submodules artifact
@@ -83,6 +84,10 @@ jobs:
             if [ "${GITHUB_REF##*/}" = "master" ]; then
               tags+=("latest")
             fi
+            export GIT_TAG=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
+            if [ "$GIT_TAG" ]; then
+              tags+=("$GIT_TAG")
+            fi
             for tag in "${tags[@]}"; do
               dest="${IMAGE_BASE}/${dest_repo}:${tag}"
               echo "Tagging image $src_img as $dest..."
@@ -105,6 +110,142 @@ jobs:
             --build-arg MIST_VERSION_NAME="${GITHUB_REF##*/}" \
             .
           docker_push "ghcr.io/${GITHUB_REPOSITORY_OWNER##*/}/api:${GITHUB_SHA}" "api"
+
+  build-landing:
+    name: Build Landing Image
+    needs: discover-submodules
+    runs-on: ubuntu-latest
+    env:
+      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
+    steps:
+      - name: Checkout code (with submodules)
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: '0'
+          submodules: recursive
+
+      - name: Download submodules artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: submodules
+
+      - name: Log in to GitHub Container Registry
+        run: echo "${GHCR_TOKEN}" | docker login ghcr.io -u "mistcommunity-bot" --password-stdin
+
+      - name: Build Landing image
+        run: |
+          set -e
+          # Define helper functions.
+          docker_pull() {
+            img=$1
+            tries=60
+            sleep_time=10
+            echo "Pulling image $img (up to $tries attempts)..."
+            for i in $(seq 1 $tries); do
+              if docker pull "$img"; then
+                echo "Image $img pulled successfully!"
+                return 0
+              fi
+              sleep $sleep_time
+            done
+            echo "Failed to pull image $img."
+            return 1
+          }
+          docker_push() {
+            local src_img=$1
+            local dest_repo=$2
+            # Define tags: commit SHA, branch slug and add "latest" for master.
+            tags=("${GITHUB_SHA}" "${GITHUB_REF##*/}")
+            if [ "${GITHUB_REF##*/}" = "master" ]; then
+              tags+=("latest")
+            fi
+            export GIT_TAG=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
+            if [ "$GIT_TAG" ]; then
+              tags+=("$GIT_TAG")
+            fi
+            for tag in "${tags[@]}"; do
+              dest="${IMAGE_BASE}/${dest_repo}:${tag}"
+              echo "Tagging image $src_img as $dest..."
+              docker tag "$src_img" "$dest"
+              echo "Pushing image $dest..."
+              docker push "$dest"
+            done
+          }
+          get_submodule_sha() {
+            grep ",$1\$" submodules.csv | cut -d, -f1
+          }
+          # Use the submodule SHA for the Landing image.
+          SRC_IMG="ghcr.io/${SUBMODULES_IMAGE}/landing:$(get_submodule_sha landing)"
+          docker_pull "$SRC_IMG"
+          docker_push "$SRC_IMG" "landing"
+
+  build-ui:
+    name: Build UI Image
+    needs: discover-submodules
+    runs-on: ubuntu-latest
+    env:
+      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
+    steps:
+      - name: Checkout code (with submodules)
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: '0'
+          submodules: recursive
+
+      - name: Download submodules artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: submodules
+
+      - name: Log in to GitHub Container Registry
+        run: echo "${GHCR_TOKEN}" | docker login ghcr.io -u "mistcommunity-bot" --password-stdin
+
+      - name: Build UI image
+        run: |
+          set -e
+          # Define helper functions.
+          docker_pull() {
+            img=$1
+            tries=60
+            sleep_time=10
+            echo "Pulling image $img (up to $tries attempts)..."
+            for i in $(seq 1 $tries); do
+              if docker pull "$img"; then
+                echo "Image $img pulled successfully!"
+                return 0
+              fi
+              sleep $sleep_time
+            done
+            echo "Failed to pull image $img."
+            return 1
+          }
+          docker_push() {
+            local src_img=$1
+            local dest_repo=$2
+            # Define tags: commit SHA, branch slug and add "latest" for master.
+            tags=("${GITHUB_SHA}" "${GITHUB_REF##*/}")
+            if [ "${GITHUB_REF##*/}" = "master" ]; then
+              tags+=("latest")
+            fi
+            export GIT_TAG=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
+            if [ "$GIT_TAG" ]; then
+              tags+=("$GIT_TAG")
+            fi
+            for tag in "${tags[@]}"; do
+              dest="${IMAGE_BASE}/${dest_repo}:${tag}"
+              echo "Tagging image $src_img as $dest..."
+              docker tag "$src_img" "$dest"
+              echo "Pushing image $dest..."
+              docker push "$dest"
+            done
+          }
+          get_submodule_sha() {
+            grep ",$1\$" submodules.csv | cut -d, -f1
+          }
+          # Use the submodule SHA for the UI image.
+          SRC_IMG="ghcr.io/${SUBMODULES_IMAGE}/ui:$(get_submodule_sha ui)"
+          docker_pull "$SRC_IMG"
+          docker_push "$SRC_IMG" "ui"
 
   build-tests:
     name: Build Tests Image
@@ -187,6 +328,8 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: '0'
 
       - name: Log in to GitHub Container Registry
         run: echo "${GHCR_TOKEN}" | docker login ghcr.io -u "mistcommunity-bot" --password-stdin
@@ -202,6 +345,10 @@ jobs:
             tags=("${GITHUB_SHA}" "${GITHUB_REF##*/}")
             if [ "${GITHUB_REF##*/}" = "master" ]; then
               tags+=("latest")
+            fi
+            export GIT_TAG=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
+            if [ "$GIT_TAG" ]; then
+              tags+=("$GIT_TAG")
             fi
             for tag in "${tags[@]}"; do
               dest="${IMAGE_BASE}/${dest_repo}:${tag}"
@@ -221,6 +368,8 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: '0'
 
       - name: Install gettext for envsubst
         run: |
@@ -233,6 +382,10 @@ jobs:
           export IMG_REGISTRY="${IMAGE_BASE}"
           echo "IMG_REGISTRY=$IMG_REGISTRY"
           export IMG_TAG="${GITHUB_REF##*/}"
+          export GIT_TAG=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
+          if [ "$GIT_TAG" ]; then
+            export IMG_TAG=$GIT_TAG
+          fi
           echo "IMG_TAG=$IMG_TAG"
           export CONF_DIR=/etc/mist
           envsubst < docker-compose.yml > artifacts/docker-compose.yml
